### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by gdevenyi** [r03ert0/surfaceratio#2]
I was considering building a PR to add this directly to CIVET so it can produce local GI measures, instead of the postprocessing I currently do, but I'm not sure I can due to licencing. Would you please clarify the licence? Thanks!

**Comment by r03ert0** [comment]
hola @gdevenyi! how cool! I'll put a nice, permissive license :D. Like BSD would be good?

**Comment by r03ert0** [comment]
there you go! I added a BSD license.
Now, if you are going to use the code, I'll try to create some tests... do you have any advice for testing C code? (I've only written tests for python and javascript...)

**Comment by gdevenyi** [comment]
Great! :+1:

Sadly, I've never written any testing for c-code, only python. I know for fancy projects ctest+cmake is one way, but that would be overkill here.
